---
# tasks file for roles/ubuntu/confignagios

- name: Creating virtual host dir
  become: yes
  file:
    path: /etc/httpd/conf.d
    state: directory

- name: Configure nagios script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: Clean nagios core file
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: clean

- name: Compiling nagios core
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: Install nagios binaries
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: Install init script in nagios
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-init


- name: Installing config file in nagios
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Set permission in nagios
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Install nagios web interface
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Install co-requisite python for htpasswd
  become: yes
  apt:
    name: python3-pip
    state: latest

- name: Install htpasswd module
  become: yes
  apt:
    name: python-passlib
    state: latest

- name: Create nagiosadmin
  become: yes
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: '{{ nagadmin }}'
    password: '{{ nagadminpass }}'

- name: Restart apache
  become: yes
  service:
    name: apache2
    state: reloaded

- name: Start the nagios service
  shell: '/etc/init.d/nagios start'
